trigger:
  branches:
    include:
      - main
  paths:
    include:
      - iac/service.ingestion/**

pool:
  vmImage: "ubuntu-22.04"

variables:
  - group: tispoc
  - name: location
    value: "France Central"
  - name: deploymentName
    value: "ci-ingestion-core-$(Build.BuildId)"

stages:
  - stage: BuildInfrastructure
    displayName: "Build core infrastructure"
    jobs:
      - template: ../../../cicd/jobs/build-infra.job.yml
        parameters:
          jobName: "IngestionCore"
          deploymentName: $(deploymentName)
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          bicepFilePath: "iac/service.ingestion/main.bicep"
          azureSubscription: $(armServiceConnectionName)
