trigger: none

pool:
  vmImage: "ubuntu-22.04"

variables:
  - group: tispoc
  - name: location
    value: "France Central"
  - name: bicepFilePath
    value: "iac/service.ingestion/main.bicep"
  - name: deploymentName
    value: "release-ingestion-core-$(Build.BuildId)"

stages:
  - stage: DeployInfrastructure
    displayName: "Deploy core infrastructure"
    jobs:
      - template: ../../../cicd/jobs/deploy-infra.job.yml
        parameters:
          deploymentName: $(deploymentName)
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          bicepFilePath: $(bicepFilePath)
          azureSubscription: $(armServiceConnectionName)
