.execute database script <|

// Create metrics table
//  - Retention set to 3 days
//  - Hot caching for 1 day
.create-merge table metrics (
    timestamp: datetime,
    device_id: string,
    sensor: string,
    metric: string,
    value: dynamic,
    unit: string
    );

// View configuration
.alter-merge table metrics policy retention softdelete = 3d recoverability = disabled;
.alter table metrics policy caching hot = 1d;
.alter-merge table metrics policy ingestionbatching
```
{
    "MaximumNumberOfItems" : 25000
}
```;

// Function to monitor devices status
.create-or-alter function with (docstring='monitor devices status') devices_status_monitor()
 {
     metrics
    | summarize
        last_update = max(timestamp),
        status = case(
            take_any(sensor) == "device" and take_any(metric) == "state", iif(countif(tostring(value) == "on") > 0, "on", "$use_last$"),
            ""
        ),
        arg_max(timestamp, last_value = value)
        by bin(timestamp, 10m), device_id, sensor, metric
    | where status != ""
    | project
        device_id,
        last_update, 
        status = iff(
            status == "$use_last$", last_value,
            status
        ) 
 }

// Function to monitor devices sensors
.create-or-alter function with (docstring='monitor devices sensors') devices_sensors_monitor()
 {
     metrics
    | where isnotempty(sensor) and sensor != "device"
    | extend sensor = replace_string(sensor, "device.", "")
    | summarize
        sensors = make_set(sensor) by device_id
    | project
        device_id,
        sensors
 }

// Function to aggregate metrics over a specified period
.create-or-alter function with (docstring='aggregate metrics over a specified period') metrics_aggregator(period: timespan)
 {
     metrics
    | summarize
        computed_value = case(
            take_any(sensor) == "device", case(
                take_any(metric) == "state", iif(countif(tostring(value) == "on") > 0, "on", "$use_last$"),
                take_any(metric) == "uptime", "$use_last$",
                "$use_auto$"
            ),
            take_any(sensor) == "device.network", case(
                take_any(metric) == "bytes_received", "$use_last$",
                take_any(metric) == "bytes_sent", "$use_last$",
                take_any(metric) == "packets_dropped", "$use_last$",
                "$use_auto$"
            ),
            take_any(sensor) == "device.storage", case(
                take_any(metric) == "used_size", "$use_last$",
                take_any(metric) == "free_size", "$use_last$",
                take_any(metric) == "health", iif(countif(tostring(value) == "good") > 0, "good", "$use_last$"),
                "$use_auto$"
            ),
            take_any(sensor) == "device.battery", case(
                take_any(metric) == "time_to_empty", "$use_last$",
                "$use_auto$"
            ),
            "$use_auto$"
        ),
        avg_value = iff(gettype(take_any(value)) in ("real", "long", "int", "double"), avg(todouble(value)), double(null)),
        arg_max(timestamp, last_value = value)
        by bin(timestamp, period), device_id, sensor, metric
    | project
        timestamp,
        device_id,
        sensor,
        metric,
        value = case(
            computed_value == "$use_last$", last_value,
            computed_value == "$use_auto$", coalesce(todynamic(tostring(avg_value)), last_value),
            last_value
        )
 }
