trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/service.data/**

pool:
  vmImage: "ubuntu-22.04"

variables:
  - name: goVersion
    value: "1.26.0"
  - name: servicePath
    value: "src/service.data"

stages:
  - stage: BuildDataService
    displayName: "Build data service"
    jobs:
      - template: ../../../cicd/jobs/build-app.job.yml
        parameters:
          goVersion: $(goVersion)
          servicePath: $(servicePath)
          cmds:
            - name: "server"
              path: "cmd/server"
