// -----------------------------------------------------------------------
// metrics_1h_store :
//   One hour summarize with all intermediate aggregation values.
//
//   Retention: 365 days | Hot cache: 90 days
// -----------------------------------------------------------------------
.create-or-alter materialized-view with (docstring='one hour summarize of intermediate aggregation values')
    metrics_1h_store on table metrics_store
    {
    metrics_store
    | summarize
        avg_value = avgif(value_real, isnotnull(value_real)),
        count_on = countif(value_string == "on"),
        count_good = countif(value_string == "good"),
        group_timestamp = arg_max(timestamp, value_real, value_string)
        by bin(timestamp, 1h), device_id, sensor, metric
    }

.alter-merge materialized-view metrics_1h_store policy retention softdelete = 365d recoverability = disabled;
.alter materialized-view metrics_1h_store policy caching hot = 90d;

// -----------------------------------------------------------------------
// metrics_1h_bag :
//   Resolves intermediate aggregation values from metrics_1h_store
//   into final metric values.
//
//   Parameters:
//     - device_id : the device to filter on
//     - sensor    : the sensor to filter on (optional)
// -----------------------------------------------------------------------
.create-or-alter function with (docstring='resolves one hour of aggregated metrics into a bag of telemetry')
    metrics_1h_bag(deviceId: string, sensorName: string = "")
 {
    materialized_view('metrics_1h_store')
    | where device_id == deviceId
    | where isempty(sensorName) or sensor == sensorName
    | invoke  resolve_metrics()
    | summarize telemetry = make_bag(bag_pack(metric, value)) by group_timestamp, sensor
 }
