FROM golang:1.25.7-alpine AS builder
ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd/
COPY external/ ./external/
COPY internal/ ./internal/
RUN go build -ldflags="-s -w" -o silver-worker ./cmd/silver-worker

FROM alpine:3.22
RUN apk --no-cache add ca-certificates && \
    addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup
WORKDIR /app
COPY --from=builder /app/silver-worker .
RUN chown -R appuser:appgroup /app

USER appuser
EXPOSE 8080 8081
ENTRYPOINT ["./silver-worker"]
STOPSIGNAL SIGTERM
