parameters:
  - name: jobName
    type: string
  - name: deploymentName
    type: string
  - name: subscriptionId
    type: string
  - name: resourceGroupName
    type: string
  - name: location
    type: string
  - name: azureSubscription
    type: string
  - name: bicepFilePath
    type: string
  - name: overrideParameters
    type: string
    default: ""

jobs:
  - job: Validate${{ parameters.jobName }}Infrastructure
    displayName: "Validate ${{ parameters.jobName }} infrastructure as code"
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: "Validate bicep template"
      inputs:
        deploymentMode: "Validation"
        deploymentScope: "Resource Group"
        azureResourceManagerConnection: "${{ parameters.azureSubscription }}"
        subscriptionId: "${{ parameters.subscriptionId }}"
        action: "Create Or Update Resource Group"
        resourceGroupName: "${{ parameters.resourceGroupName }}"
        location: "${{ parameters.location }}"
        templateLocation: "Linked artifact"
        csmFile: "${{ parameters.bicepFilePath }}"
        deploymentName: "${{ parameters.deploymentName }}"
        overrideParameters: ${{ parameters.overrideParameters }}
