// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package pkg

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeServiceIngestionPkg(in *jlexer.Lexer, out *VersionDiscriminant) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeServiceIngestionPkg(out *jwriter.Writer, in VersionDiscriminant) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix[1:])
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VersionDiscriminant) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeServiceIngestionPkg(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VersionDiscriminant) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeServiceIngestionPkg(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VersionDiscriminant) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeServiceIngestionPkg(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VersionDiscriminant) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeServiceIngestionPkg(l, v)
}
func easyjson6a975c40DecodeServiceIngestionPkg1(in *jlexer.Lexer, out *TelemetryV2Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "device_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceId = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "metrics":
			if in.IsNull() {
				in.Skip()
				out.Metrics = nil
			} else {
				in.Delim('[')
				if out.Metrics == nil {
					if !in.IsDelim(']') {
						out.Metrics = make([]struct {
							Name     string `json:"name"`
							Origin   string `json:"origin"`
							Unit     string `json:"unit,omitempty"`
							Measures []struct {
								Timestamp int64       `json:"timestamp"`
								Value     interface{} `json:"value"`
							} `json:"measures"`
						}, 0, 0)
					} else {
						out.Metrics = []struct {
							Name     string `json:"name"`
							Origin   string `json:"origin"`
							Unit     string `json:"unit,omitempty"`
							Measures []struct {
								Timestamp int64       `json:"timestamp"`
								Value     interface{} `json:"value"`
							} `json:"measures"`
						}{}
					}
				} else {
					out.Metrics = (out.Metrics)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Name     string `json:"name"`
						Origin   string `json:"origin"`
						Unit     string `json:"unit,omitempty"`
						Measures []struct {
							Timestamp int64       `json:"timestamp"`
							Value     interface{} `json:"value"`
						} `json:"measures"`
					}
					easyjson6a975c40Decode(in, &v1)
					out.Metrics = append(out.Metrics, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeServiceIngestionPkg1(out *jwriter.Writer, in TelemetryV2Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"metrics\":"
		out.RawString(prefix)
		if in.Metrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Metrics {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode(out, v3)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TelemetryV2Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeServiceIngestionPkg1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TelemetryV2Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeServiceIngestionPkg1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TelemetryV2Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeServiceIngestionPkg1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TelemetryV2Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeServiceIngestionPkg1(l, v)
}
func easyjson6a975c40Decode(in *jlexer.Lexer, out *struct {
	Name     string `json:"name"`
	Origin   string `json:"origin"`
	Unit     string `json:"unit,omitempty"`
	Measures []struct {
		Timestamp int64       `json:"timestamp"`
		Value     interface{} `json:"value"`
	} `json:"measures"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "origin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Origin = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "measures":
			if in.IsNull() {
				in.Skip()
				out.Measures = nil
			} else {
				in.Delim('[')
				if out.Measures == nil {
					if !in.IsDelim(']') {
						out.Measures = make([]struct {
							Timestamp int64       `json:"timestamp"`
							Value     interface{} `json:"value"`
						}, 0, 2)
					} else {
						out.Measures = []struct {
							Timestamp int64       `json:"timestamp"`
							Value     interface{} `json:"value"`
						}{}
					}
				} else {
					out.Measures = (out.Measures)[:0]
				}
				for !in.IsDelim(']') {
					var v4 struct {
						Timestamp int64       `json:"timestamp"`
						Value     interface{} `json:"value"`
					}
					easyjson6a975c40Decode1(in, &v4)
					out.Measures = append(out.Measures, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode(out *jwriter.Writer, in struct {
	Name     string `json:"name"`
	Origin   string `json:"origin"`
	Unit     string `json:"unit,omitempty"`
	Measures []struct {
		Timestamp int64       `json:"timestamp"`
		Value     interface{} `json:"value"`
	} `json:"measures"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.String(string(in.Origin))
	}
	if in.Unit != "" {
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"measures\":"
		out.RawString(prefix)
		if in.Measures == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Measures {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode1(out, v6)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a975c40Decode1(in *jlexer.Lexer, out *struct {
	Timestamp int64       `json:"timestamp"`
	Value     interface{} `json:"value"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode1(out *jwriter.Writer, in struct {
	Timestamp int64       `json:"timestamp"`
	Value     interface{} `json:"value"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeServiceIngestionPkg2(in *jlexer.Lexer, out *TelemetryV1Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "device_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceId = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]struct {
							Name   string      `json:"name"`
							Origin string      `json:"origin"`
							Unit   string      `json:"unit,omitempty"`
							Value  interface{} `json:"value"`
						}, 0, 1)
					} else {
						out.Data = []struct {
							Name   string      `json:"name"`
							Origin string      `json:"origin"`
							Unit   string      `json:"unit,omitempty"`
							Value  interface{} `json:"value"`
						}{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v7 struct {
						Name   string      `json:"name"`
						Origin string      `json:"origin"`
						Unit   string      `json:"unit,omitempty"`
						Value  interface{} `json:"value"`
					}
					easyjson6a975c40Decode2(in, &v7)
					out.Data = append(out.Data, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeServiceIngestionPkg2(out *jwriter.Writer, in TelemetryV1Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Data {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40Encode2(out, v9)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TelemetryV1Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeServiceIngestionPkg2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TelemetryV1Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeServiceIngestionPkg2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TelemetryV1Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeServiceIngestionPkg2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TelemetryV1Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeServiceIngestionPkg2(l, v)
}
func easyjson6a975c40Decode2(in *jlexer.Lexer, out *struct {
	Name   string      `json:"name"`
	Origin string      `json:"origin"`
	Unit   string      `json:"unit,omitempty"`
	Value  interface{} `json:"value"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "origin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Origin = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40Encode2(out *jwriter.Writer, in struct {
	Name   string      `json:"name"`
	Origin string      `json:"origin"`
	Unit   string      `json:"unit,omitempty"`
	Value  interface{} `json:"value"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.String(string(in.Origin))
	}
	if in.Unit != "" {
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeServiceIngestionPkg3(in *jlexer.Lexer, out *TelemetryLegacyEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "device_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceId = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.State = string(in.String())
			}
		case "uptime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uptime = float64(in.Float64())
			}
		case "cpu_usage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CpuUsage = float64(in.Float64())
			}
		case "cpu_memory":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CpuMemory = float64(in.Float64())
			}
		case "cpu_temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CpuTemperature = float64(in.Float64())
			}
		case "network_latency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NetworkLatency = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeServiceIngestionPkg3(out *jwriter.Writer, in TelemetryLegacyEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"uptime\":"
		out.RawString(prefix)
		out.Float64(float64(in.Uptime))
	}
	{
		const prefix string = ",\"cpu_usage\":"
		out.RawString(prefix)
		out.Float64(float64(in.CpuUsage))
	}
	{
		const prefix string = ",\"cpu_memory\":"
		out.RawString(prefix)
		out.Float64(float64(in.CpuMemory))
	}
	{
		const prefix string = ",\"cpu_temperature\":"
		out.RawString(prefix)
		out.Float64(float64(in.CpuTemperature))
	}
	{
		const prefix string = ",\"network_latency\":"
		out.RawString(prefix)
		out.Float64(float64(in.NetworkLatency))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TelemetryLegacyEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeServiceIngestionPkg3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TelemetryLegacyEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeServiceIngestionPkg3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TelemetryLegacyEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeServiceIngestionPkg3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TelemetryLegacyEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeServiceIngestionPkg3(l, v)
}
